name: Package Porter CI

on:
  push:
    branches:
      - "**" # This will run the workflow on push to any branch

env:
  CARGO_TERM_COLOR: always

jobs:
  install-rust:
    name: Install Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
    outputs:
      toolchain: ${{ steps.rustc.outputs.version }}

  build:
    name: Build
    needs: install-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ needs.install-rust.outputs.toolchain }}
      - name: Build
        run: cargo build --verbose

  test:
    name: Test
    needs: install-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ needs.install-rust.outputs.toolchain }}
      - name: Run tests
        run: cargo test --all-features --verbose

  lint:
    name: Lint
    needs: install-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ needs.install-rust.outputs.toolchain }}
          components: rustfmt, clippy
      - name: Run clippy
        run: cargo clippy --all-features -- -D warnings
      - name: Check formatting
        run: cargo fmt -- --check
