name: Package Porter CI

on:
  push:
    branches:
      - "**" # This will run the workflow on push to any branch
  pull_request:
    branches:
      - "**" # This will run the workflow on pull requests to any branch

env:
  CARGO_TERM_COLOR: always

jobs:
  install-rust:
    uses: ./.github/workflows/rust-installation.yml

  build:
    name: Build
    needs: install-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rust-installation.yml
      - name: Build
        run: cargo build --verbose

  test:
    name: Test
    needs: install-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rust-installation.yml
      - name: Run tests
        run: cargo test --verbose

  lint:
    name: Lint
    needs: install-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rust-installation.yml
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Check formatting
        run: cargo fmt -- --check
